[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
solc = "0.8.18"

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[fuzz]
runs = 1500
max_test_rejects = 100_000_000

[invariant]
runs = 10_000
depth = 20
# fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
